baseURL = 'furqantariq.github.io'
languageCode = 'en-us'
title = "furqan's homepage"
theme = 'cactus'
copyright = "Furqan Tariq"
googleAnalytics = "G-3SNBC5QD82"

# theme color
# available options: dark, light, white, classic
[params]
    colortheme = "light"
    description = "furqan's homepage"
    images = ["images/share.jpg"]
    mainSection = "posts"
    mainSectionTitle = "Posts"
    showAllPostsOnHomePage = false
    postsOnHomePage = 20
    tagsOverview = false
    showProjectsList = false
    projectsUrl = "https://github.com/furqantariq"
    mathjax = true
    

# navigation
[[menu.main]]
    name = "home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "posts"
    url = "/posts"
    weight = 2

[[menu.main]]
    name = "tags"
    url = "/tags"
    weight = 3


# social media links
[[params.social]]
    name = "twitter"
    link = "https://twitter.com/kickflip_er

[[params.social]]
    name = "github"
    link = "https://github.com/furqantariq"

[[params.social]]
    name = "youtube"
    link = "https://www.youtube.com/channel/UCi5cM4fLu56MCDHlgN_phJA"

[[params.social]]
    name = "twitch"
    link = "https://twitch.tv/frezzhberry"

[[params.social]]
    name = "steam"
    link = "https://steamcommunity.com/id/furqan"
