baseURL = 'https://furqantariq.github.io/'
languageCode = 'en-us'
title = 'furqan'

theme = 'cactus'

[params]
description = ""
showAllPostsOnHomePage = true

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)']]



[[menu.main]]
name = "blog"
url = "/"
weight = 1

[[menu.main]]
name = "twitch"
url = "/twitch"
weight = 2
