baseURL = 'https://furqantariq.github.io/'
languageCode = 'en-us'
title = 'furqan'
author = "Furqan"
theme = 'cactus'

[params]
description = "Hi there,"
showAllPostsOnHomePage = true


[services]
  [services.googleAnalytics]
    id = 'G-7HB4E08XLS'

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)']]


[[menu.main]]
name = "blog"
url = "/"
weight = 1

[[menu.main]]
name = "twitch"
url = "/twitch"
weight = 2

[[params.social]]
  name = "twitch"
  link = "https://twitch.tv/amoebatron"

[[params.social]]
  name = "strava"
  link = "https://www.strava.com/athletes/120590510"

[[params.social]]
  name = "instagram"
  link = "https://www.instagram.com/furqantq"

[[params.social]]
  name = "youtube"
  link = "https://www.youtube.com/@furqantq"